#!/bin/bash

create() {
  TARGET_SOURCE_DIRECTORY="${1}"
  terraform -chdir="${TARGET_SOURCE_DIRECTORY}" init > /dev/null
  terraform -chdir="${TARGET_SOURCE_DIRECTORY}" apply -auto-approve -var="platform_instance_name=crow-sandbox-a3b"
}

destroy() {
  TARGET_SOURCE_DIRECTORY="${1}"
  terraform -chdir="${TARGET_SOURCE_DIRECTORY}" destroy -auto-approve &
}

apply_all() {
  COMMAND="${1}"

  while read -r DIRECTORY; do
    EXAMPLE_DIR="${PWD}/"$(basename "${DIRECTORY}")
    echo "[${COMMAND}] ${EXAMPLE_DIR}"
    "${COMMAND}" "${EXAMPLE_DIR}"
    echo ""
  done <<< "$(find . -mindepth 1 -maxdepth 1 -type d)"
}

COMMAND="${1}"

apply_all "${COMMAND?}"
